import { productImageSrc } from "@/lib/product-image";
import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "@/components/site-header";
import { HeadphoneComparisonPicker } from "@/components/headphone-comparison-picker";
import { getSmartphoneCollection } from "@/lib/smartphone-queries";
export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Compare smartphones",description:"Choose two phones and compare sourced specifications, practical trade-offs, and community picks.",alternates:{canonical:"/category/smartphones"}};
export default async function SmartphonesPage() {
  let data:Awaited<ReturnType<typeof getSmartphoneCollection>>={products:[],comparisons:[]};let unavailable=false;
  try {data=await getSmartphoneCollection();} catch(error){console.error("Smartphone collection unavailable",error);unavailable=true;}
  const byId=new Map(data.products.map((p)=>[p.id,p]));
  return <main className="min-h-screen"><SiteHeader/><div className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><Link href="/categories" className="text-link">All categories</Link><h1 className="mt-6 text-4xl font-black">Compare smartphones</h1><p className="mt-3 mb-7 text-slate-400">{data.products.length} published phones · {data.comparisons.length} comparisons. Explore the trade-offs that matter to you.</p><HeadphoneComparisonPicker products={data.products} comparisons={data.comparisons} category="smartphones" dataUnavailable={unavailable}/><section className="mt-12"><h2 className="text-2xl font-black">Phone catalog</h2><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{data.products.map((p)=><Link href={`/catalog/${p.slug}`} key={p.id} className="rounded-3xl border border-white/10 bg-white/[.035] p-5 hover:border-cyan-300/40"><div className="flex h-52 items-center justify-center rounded-2xl bg-white p-4">{p.imageUrl && <img src={productImageSrc(p.imageUrl)} alt={p.canonicalName} className="h-full w-full object-contain" loading="lazy"/>}</div><p className="mt-5 text-sm font-bold text-cyan-300">{p.brand}</p><h3 className="mt-1 text-xl font-black">{p.canonicalName}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{p.description}</p></Link>)}</div></section><section id="comparisons" className="mt-12"><h2 className="text-2xl font-black">All smartphone matchups</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{data.comparisons.map((c)=><Link key={c.id} href={`/compare/smartphones/${c.slug}`} className="rounded-2xl border border-white/10 p-5 font-bold hover:border-cyan-300/40">{byId.get(c.leftProductId)?.canonicalName} <span className="text-slate-500">vs</span> {byId.get(c.rightProductId)?.canonicalName}<span className="mt-2 block text-sm font-normal text-cyan-200">{c.coveragePercent}% scoring coverage</span></Link>)}</div>{!unavailable && data.comparisons.length === 0 && <p className="mt-4 text-slate-400">The first research batch is awaiting publication approval.</p>}</section></div></main>;
}
