import { ComparisonPageSelector } from "@/components/comparison-page-selector";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/site-header";
import { ExtendedCategoryComparisonExperience } from "@/components/extended-category-comparison-experience";
import { DecisionAnalyticsView } from "@/components/decision-analytics-view";
import { getExtendedCategoryComparison } from "@/lib/extended-category-queries";
import { extendedCategoryModels,isExtendedCategory } from "@/lib/extended-category-specs";
import { getPublicOffers } from "@/lib/offer-queries";
export const dynamic="force-dynamic";
type Props={params:Promise<{category:string;comparison:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>};
export async function generateMetadata({params,searchParams}:Props):Promise<Metadata>{const p=await params;if(!isExtendedCategory(p.category))return{title:"Comparison unavailable",robots:{index:false,follow:false}};const found=await getExtendedCategoryComparison(p.category,p.comparison).catch(()=>null);if(!found)return{title:"Comparison unavailable",robots:{index:false,follow:false}};return{title:`${found.left.canonicalName} vs ${found.right.canonicalName}`,description:`Compare sourced ${extendedCategoryModels[p.category].name.toLowerCase()} specifications and category-specific scores.`,alternates:{canonical:`/compare/${p.category}/${found.record.slug}`},robots:{index:Object.keys(await searchParams).length===0,follow:true}};}
export default async function ExtendedComparisonPage({params}:Props){const p=await params;if(!isExtendedCategory(p.category))notFound();let found:Awaited<ReturnType<typeof getExtendedCategoryComparison>>;try{found=await getExtendedCategoryComparison(p.category,p.comparison);}catch(error){console.error("Extended comparison unavailable",error);return <main><SiteHeader/><div className="mx-auto max-w-4xl p-8"><h1 className="text-3xl font-black">Comparison temporarily unavailable</h1><p className="mt-4">Please refresh in a moment.</p></div></main>}if(!found)notFound();const{record,left,right,collection}=found;const offers=await getPublicOffers([left.id,right.id]).catch(()=>new Map());const related=collection.comparisons.filter((c)=>c.id!==record.id&&[c.leftProductId,c.rightProductId].some((id)=>id===left.id||id===right.id)).slice(0,6);return <main className="min-h-screen"><SiteHeader/><DecisionAnalyticsView eventName="comparison_viewed" details={{categorySlug:p.category,comparisonSlug:record.slug,productIds:[left.id,right.id]}}/><div className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><Link href={`/category/${p.category}`} className="text-link">{extendedCategoryModels[p.category].name}</Link><ComparisonPageSelector category={p.category} leftId={left.id} rightId={right.id} collection={collection} /><ExtendedCategoryComparisonExperience category={p.category} left={left} right={right} comparisonSlug={record.slug} offers={{left:offers.get(left.id)??[],right:offers.get(right.id)??[]}}/><section className="mt-10"><h2 className="text-2xl font-black">Keep comparing</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{related.map((c)=><Link key={c.id} href={`/compare/${p.category}/${c.slug}`} className="rounded-xl border border-white/10 p-4 text-cyan-200">{collection.products.find((x)=>x.id===c.leftProductId)?.canonicalName} vs {collection.products.find((x)=>x.id===c.rightProductId)?.canonicalName}</Link>)}</div></section></div></main>}
