"use client";
import { ComparisonProductScore } from "@/components/comparison-product-score";
import { ComparisonSpecifications } from "@/components/comparison-specifications";
import { WinnerIndicator } from "@/components/winner-indicator";
import { useComparisonPreset } from "@/hooks/use-comparison-preset";
import { CatalogProductImage } from "@/components/catalog-product-image";
import { Button } from "@/components/ui/button";
import { CommunityVote } from "@/components/community-vote";
import { RetailerOffers } from "@/components/retailer-offers";
import type { PublicOffer } from "@/lib/offers";
import { draftExtendedVerdict,extendedCategoryModels,formatExtendedSpec,scoreExtendedComparison,verifiedExtendedSpecs,type ExtendedCategorySlug,type ExtendedProduct } from "@/lib/extended-category-specs";

export function ExtendedSpecifications({category,product}:{category:ExtendedCategorySlug;product:ExtendedProduct}){const model=extendedCategoryModels[category],specs=verifiedExtendedSpecs(category,product);let sources:Record<string,{sourceUrl:string;retrievedAt:string;notes?:string}>={};try{sources=JSON.parse(product.specProvenanceJson??"{}");}catch{}return <dl className="mt-5 overflow-hidden rounded-2xl border border-white/10">{model.fields.map((field)=><div key={field.key} className="grid gap-2 border-b border-white/10 p-4 last:border-0 sm:grid-cols-2"><dt className="text-slate-400">{field.label}</dt><dd className="min-w-0 break-words"><strong>{formatExtendedSpec(category,field.key,specs[field.key])}</strong>{specs[field.key]!==undefined&&sources[field.key]&&<p className="mt-1 text-sm text-slate-400"><a className="text-cyan-300 underline" href={sources[field.key].sourceUrl} target="_blank" rel="noreferrer">Manufacturer source</a> · {sources[field.key].retrievedAt.slice(0,10)}{sources[field.key].notes&&<span className="mt-1 block">{sources[field.key].notes}</span>}</p>}</dd></div>)}</dl>}

export function ExtendedCategoryComparisonExperience({category,left,right,comparisonSlug,preview=false,offers={left:[],right:[]}}:{category:ExtendedCategorySlug;left:ExtendedProduct;right:ExtendedProduct;comparisonSlug:string;preview?:boolean;offers?:{left:PublicOffer[];right:PublicOffer[]}}){const model=extendedCategoryModels[category],keys=Object.keys(model.presets),[preset,setPreset]=useComparisonPreset(keys,preview),score=scoreExtendedComparison(category,left,right,preset),verdict=draftExtendedVerdict(category,left,right,preset),a=verifiedExtendedSpecs(category,left),b=verifiedExtendedSpecs(category,right);return <div className="mt-8 space-y-8">
  {preview&&<p className="rounded-xl border border-amber-300/30 p-4 text-amber-200">Unpublished research preview. Voting and retailer links are disabled.</p>}
  <section className="winner-product-pair">{[left,right].map((p)=><article key={p.id} className="flex min-w-0 flex-col rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="comparison-product-image flex h-56 items-center justify-center rounded-2xl bg-white p-4"><CatalogProductImage product={p}/></div><p className="mt-5 text-sm font-bold text-cyan-300">{p.brand}</p><h2 className="mt-1 text-2xl font-black">{p.canonicalName}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{p.description}</p><ComparisonProductScore score={p.id === left.id ? score.scoreLeft : score.scoreRight} eligible={score.eligible} preset={model.presets[preset].label} /></article>)}<WinnerIndicator leftScore={score.scoreLeft} rightScore={score.scoreRight} eligible={score.eligible} leftLabel={left.canonicalName} rightLabel={right.canonicalName} scoreLabel={model.presets[preset].label} /></section>
  <section className="rounded-3xl border border-white/10 p-6"><p className="section-kicker text-center">Category-specific score</p><h2 className="comparison-priorities-heading mt-2 text-2xl font-black">What matters most to you?</h2><div className="comparison-priorities-options mt-4 flex flex-wrap gap-2">{keys.map((key)=><Button key={key} variant={preset===key?"default":"outline"} aria-pressed={preset===key} onClick={()=>setPreset(key)}>{model.presets[key].label}</Button>)}</div><p className="mt-3 text-sm text-slate-400">{model.presets[preset].description}</p>{score.eligible?<div className="mt-6 grid grid-cols-2 gap-4 text-center">{[score.scoreLeft,score.scoreRight].map((value,i)=><div key={i}><p className="text-sm text-slate-400">{i===0?left.canonicalName:right.canonicalName}</p><p className="mt-2 text-4xl font-black text-cyan-200">{value}<span className="text-base text-slate-400"> / 100</span></p></div>)}</div>:<p className="mt-6 font-semibold text-amber-200">{score.unavailableReason}</p>}<p className="mt-4 text-sm text-slate-400">{score.coveragePercent}% supported scoring weight · {score.sharedFields} shared fields.</p><details className="mt-4"><summary className="cursor-pointer font-bold text-cyan-200">How this score works</summary><ul className="mt-3 space-y-2 text-sm text-slate-400">{score.factors.map((f)=><li key={f.key}>{f.label}: {f.weight}% · {f.available?f.winner==="tie"?"equal":`${f.winner==="left"?left.canonicalName:right.canonicalName} has the favorable value`:"excluded because evidence is missing or not applicable"}</li>)}</ul><p className="mt-3 text-sm text-slate-400">{model.limitations}</p></details></section>
  <section><h2 className="text-2xl font-black">Side-by-side specifications</h2><ComparisonSpecifications leftName={left.canonicalName} rightName={right.canonicalName} rows={model.fields.map((f)=>({key:f.key,label:f.label,left:formatExtendedSpec(category,f.key,a[f.key]),right:formatExtendedSpec(category,f.key,b[f.key])}))} /></section>
  <section className="rounded-3xl border border-white/10 p-6"><p className="section-kicker">Evidence-based guidance · {model.presets[preset].label} model</p><h2 className="mt-2 text-2xl font-black">{verdict.headline}</h2><p className="mt-3 leading-7 text-slate-400">{verdict.summary}</p><div className="mt-5 grid gap-5 md:grid-cols-2"><p>{verdict.buyLeft}</p><p>{verdict.buyRight}</p></div><div className="mt-5 flex flex-wrap gap-5 text-sm"><a href={left.sourceUrl} target="_blank" rel="noreferrer" className="text-link">{left.canonicalName} source</a><a href={right.sourceUrl} target="_blank" rel="noreferrer" className="text-link">{right.canonicalName} source</a></div></section>
  {!preview&&<><CommunityVote comparison={comparisonSlug} products={[{slug:left.slug,shortName:left.canonicalName},{slug:right.slug,shortName:right.canonicalName}]} useCaseKey={preset} attributeOptions={model.fields.filter((f)=>f.direction&&a[f.key]!==undefined&&b[f.key]!==undefined).map((f)=>({key:f.key,label:f.label}))}/><div className="grid gap-5 md:grid-cols-2"><RetailerOffers productName={left.canonicalName} offers={offers.left} comparisonSlug={comparisonSlug}/><RetailerOffers productName={right.canonicalName} offers={offers.right} comparisonSlug={comparisonSlug}/></div></>}
  </div>}
