"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { validateResearchBatch, researchCatalogProduct, researchComparisons, type ResearchBatch } from "@/lib/research-contract";

type BatchRow={id:string;digest:string;title:string;status:string;uploadedAt:string;payloadJson:string};
export function ResearchConsole({bundled,initial}: {bundled:ResearchBatch[];initial:BatchRow[]}) {
  const [rows,setRows]=useState(initial);const [busy,setBusy]=useState(()=>bundled.some((b)=>!initial.some((r)=>r.id===b.id)));const [message,setMessage]=useState("");const started=useRef(false);
  const refresh=useCallback(async()=>{const r=await fetch("/api/admin/research");const data=await r.json();if(!r.ok)throw new Error(data.error);setRows(data.batches);},[]);
  const action=async(payload:unknown)=>{const response=await fetch("/api/admin/research",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not save research.");return data;};
  useEffect(()=>{
    if(started.current)return;started.current=true;
    const missing=bundled.filter((b)=>!initial.some((row)=>row.id===b.id));if(!missing.length)return;
    (async()=>{for(const batch of missing)await action({action:"upload",batch});await refresh();setMessage("Research uploaded automatically. Publication is waiting for your approval.");})().catch((error)=>setMessage(error.message)).finally(()=>setBusy(false));
  },[bundled,initial,refresh]);
  const upload=async(file:File|undefined)=>{if(!file)return;setBusy(true);try{if(file.size>500_000)throw new Error("Upload a research JSON file smaller than 500 KB.");const batch=validateResearchBatch(JSON.parse(await file.text()));await action({action:"upload",batch});await refresh();setMessage("Research uploaded. Live products remain unchanged until you publish the batch.");}catch(error){setMessage(error instanceof Error?error.message:"Upload failed.");}finally{setBusy(false);}};
  const update=async(row:BatchRow,operation:"publish"|"reject")=>{setBusy(true);try{const r=await action({action:operation,id:row.id,digest:row.digest});await refresh();setMessage(operation==="publish"?`Published ${r.products??"the batch's"} products and ${r.comparisons??"all eligible"} comparisons.`:"Batch rejected.");}catch(error){setMessage(error instanceof Error?error.message:"Could not update the batch.");}finally{setBusy(false);}};
  return <div className="space-y-7"><section className="rounded-3xl border border-white/10 p-6"><h2 className="text-xl font-black">Research uploads</h2><p className="mt-3 leading-7 text-slate-400">Research is uploaded as a whole batch with sources, dates, and generated matchups. You approve publication once for the batch. Missing values stay unknown; new research does not erase established facts.</p><label className="mt-4 block text-sm font-bold">Upload a research batch (JSON)<Input className="mt-2" type="file" accept="application/json,.json" disabled={busy} onChange={(e)=>void upload(e.target.files?.[0])}/></label><p className="mt-3 text-sm text-slate-400">The existing Headphones CSV importer remains in the <Link href="/admin/ingestion" className="text-cyan-300 underline">Product Agent Console</Link>.</p></section>{message && <p role="status" className="break-words rounded-xl border border-cyan-300/20 p-4 text-cyan-100">{message}</p>}{busy && <p role="status" className="text-slate-400">Saving research…</p>}{rows.map((row)=>{let batch:ResearchBatch;try{batch=validateResearchBatch(JSON.parse(row.payloadJson));}catch{return <p key={row.id} role="alert">{row.title}: this stored batch needs correction before it can be opened.</p>;}const products=batch.products.map((p)=>researchCatalogProduct(p,batch.category,batch.researchedAt));const pairs=researchComparisons(products,batch.category,batch.researchedAt);return <article key={row.id} className="rounded-3xl border border-white/10 bg-white/[.025] p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><h2 className="text-2xl font-black">{row.title}</h2><span className="rounded-full border border-white/15 px-3 py-1 text-sm font-bold capitalize">{row.status}</span></div><p className="mt-3 text-slate-400">{batch.products.length} products · {pairs.length} eligible matchups · researched {batch.researchedAt.slice(0,10)}</p><div className="mt-4 flex flex-wrap gap-3"><Link className="text-link" href={`/admin/research/${row.id}`}>Preview products and comparisons</Link><a className="text-link" href={`/api/admin/research/${row.id}`}>Download research</a></div><details className="mt-5"><summary className="cursor-pointer font-semibold">Products in this batch</summary><ul className="mt-3 space-y-3">{batch.products.map((p)=><li key={p.slug} className="border-b border-white/10 pb-3"><strong>{p.canonicalName}</strong><span className="block text-sm text-slate-400">{p.configuration} · {p.region} · {Object.keys(p.specs).length} sourced fields</span></li>)}</ul></details>{row.status==="pending" && <div className="mt-6 flex flex-wrap gap-3"><Button disabled={busy} onClick={()=>void update(row,"publish")}>Approve &amp; publish batch</Button><Button variant="outline" disabled={busy} onClick={()=>void update(row,"reject")}>Reject batch</Button></div>}</article>})}{!busy && rows.length===0 && <p className="text-slate-400">No uploaded batches yet.</p>}</div>;
}
