"use client";
import { ComparisonProductScore } from "@/components/comparison-product-score";
import { ComparisonSpecifications } from "@/components/comparison-specifications";
import { WinnerIndicator } from "@/components/winner-indicator";
import { CatalogProductImage } from "@/components/catalog-product-image";
import { useComparisonPreset } from "@/hooks/use-comparison-preset";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { CommunityVote } from "@/components/community-vote";
import { RetailerOffers } from "@/components/retailer-offers";
import { trackDecisionEvent } from "@/lib/analytics-client";
import type { PublicOffer } from "@/lib/offers";
import { draftSmartphoneVerdict, formatSmartphoneSpec, scoreSmartphoneComparison, smartphoneFields, smartphonePresets, verifiedSmartphoneSpecs, type SmartphonePreset, type SmartphoneProduct } from "@/lib/smartphone-specs";

export function SmartphoneSpecifications({ product }: {product:SmartphoneProduct}) {
  const specs=verifiedSmartphoneSpecs(product);
  let sources: Record<string,{sourceUrl:string;retrievedAt:string;notes?:string}>={};
  try { sources=JSON.parse(product.specProvenanceJson ?? "{}") ?? {}; } catch {}
  return <dl className="mt-5 overflow-hidden rounded-2xl border border-white/10">{smartphoneFields.map((field)=><div key={field.key} className="grid gap-2 border-b border-white/10 p-4 last:border-0 sm:grid-cols-2"><dt className="text-slate-400">{field.label}</dt><dd className="min-w-0 break-words"><strong>{formatSmartphoneSpec(field.key,specs[field.key])}</strong>{sources[field.key] && <p className="mt-1 text-sm text-slate-400"><a className="text-cyan-300 underline" href={sources[field.key].sourceUrl} target="_blank" rel="noreferrer">Manufacturer source</a> · {sources[field.key].retrievedAt.slice(0,10)}{sources[field.key].notes && <span className="block mt-1">{sources[field.key].notes}</span>}</p>}</dd></div>)}</dl>;
}

export function SmartphoneComparisonExperience({left,right,comparisonSlug,preview=false,offers={left:[],right:[]}}:{left:SmartphoneProduct;right:SmartphoneProduct;comparisonSlug:string;preview?:boolean;offers?:{left:PublicOffer[];right:PublicOffer[]}}) {
  const [preset,setPreset]=useComparisonPreset(Object.keys(smartphonePresets) as SmartphonePreset[],preview);
  const score=scoreSmartphoneComparison(left,right,preset); const verdict=draftSmartphoneVerdict(left,right,preset);
  const a=verifiedSmartphoneSpecs(left);const b=verifiedSmartphoneSpecs(right);
  return <div className="mt-8 space-y-8">
    {preview && <p className="rounded-xl border border-amber-300/30 p-4 text-amber-200">Unpublished research preview. Voting and retailer links become available after publication.</p>}
    <div className="winner-product-pair">{[left,right].map((p)=><article key={p.id} className="flex min-w-0 flex-col rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="comparison-product-image flex h-64 items-center justify-center rounded-2xl bg-white p-5"><CatalogProductImage product={p} /></div><h2 className="mt-5 text-2xl font-black">{p.canonicalName}</h2><p className="mt-2 text-slate-400">{p.description}</p>{!preview && <Link href={`/catalog/${p.slug}`} className="text-link mt-3">Product and sources</Link>}<ComparisonProductScore score={p.id === left.id ? score.scoreLeft : score.scoreRight} eligible={score.eligible} preset={smartphonePresets[preset].label} /></article>)}<WinnerIndicator leftScore={score.scoreLeft} rightScore={score.scoreRight} eligible={score.eligible} leftLabel={left.canonicalName} rightLabel={right.canonicalName} scoreLabel={smartphonePresets[preset].label} /></div>
    <section className="comparison-shell p-5 sm:p-7"><h2 className="comparison-priorities-heading text-2xl font-black">What matters to you?</h2><div className="comparison-priorities-options mt-4 flex flex-wrap gap-2" aria-label="Comparison priorities">{(Object.keys(smartphonePresets) as SmartphonePreset[]).map((key)=><Button key={key} variant={preset === key ? "default":"outline"} aria-pressed={preset === key} onClick={()=>{setPreset(key);if(!preview)trackDecisionEvent("preset_changed",{categorySlug:"smartphones",comparisonSlug,presetKey:key,productIds:[left.id,right.id]});}}>{smartphonePresets[key].label}</Button>)}</div><div className="mt-6" aria-live="polite">{score.eligible ? <div className="grid grid-cols-2 gap-4 text-center">{[score.scoreLeft,score.scoreRight].map((value,i)=><div key={i}><p className="text-sm text-slate-400">{i===0?left.canonicalName:right.canonicalName}</p><p className="mt-2 text-4xl font-black text-cyan-200">{value}<span className="text-base text-slate-400"> / 100</span></p></div>)}</div> : <p className="font-semibold text-amber-200">Not enough shared evidence for this score. A value score needs a sourced reference price for both products.</p>}<p className="mt-4 text-sm text-slate-400">{score.coveragePercent}% of the {smartphonePresets[preset].label.toLowerCase()} scoring weight is supported by shared sources. {score.sharedFields} shared fields.</p></div><p className="mt-4 leading-7 text-slate-300">These are relative specification scores, not lab ratings. Price, weight, refresh rate, storage, and wireless charging count. Camera resolution, chipset names, and battery capacity don’t establish quality, speed, or endurance.</p><details className="mt-4"><summary className="cursor-pointer font-bold text-cyan-200">How the score is calculated</summary><ul className="mt-3 space-y-2 text-sm text-slate-400">{score.factors.map((f)=><li key={f.key}>{f.label}: {f.weight}% weight · {f.available ? f.winner === "tie" ? "Equal" : `${f.winner === "left" ? left.canonicalName : right.canonicalName} has the favorable value` : "Excluded: missing source"}</li>)}</ul><p className="mt-3 text-sm text-slate-400">Each numeric factor awards a proportional share to each phone; lower price and weight are preferred. Missing factors are excluded, and remaining weights are normalized. Scores require 70% weighted coverage and eight shared fields. Display size and operating system are personal choices. Reference prices may be launch MSRP; check current offers before buying.</p></details></section>
    <section><h2 className="text-2xl font-black">Side-by-side specifications</h2><p className="mt-3 text-sm leading-6 text-slate-400">Prices are sourced reference prices, including launch MSRP, rather than live store offers. Storage and regional configurations may differ; open each product’s source record for configuration and measurement notes.</p><ComparisonSpecifications leftName={left.canonicalName} rightName={right.canonicalName} rows={smartphoneFields.map((f)=>({key:f.key,label:f.label,left:formatSmartphoneSpec(f.key,a[f.key]),right:formatSmartphoneSpec(f.key,b[f.key])}))} /></section>
    <section className="rounded-3xl border border-white/10 p-6"><p className="section-kicker">Evidence-based guidance · {smartphonePresets[preset].label} model</p><h2 className="mt-2 text-2xl font-black">{verdict.headline}</h2><p className="mt-3 leading-7 text-slate-400">{verdict.summary}</p><div className="mt-5 grid gap-5 md:grid-cols-2"><p>{verdict.buyLeft}</p><p>{verdict.buyRight}</p></div><div className="mt-5 flex flex-wrap gap-5 text-sm"><a href={left.sourceUrl} target="_blank" rel="noreferrer" className="text-link">{left.canonicalName} source</a><a href={right.sourceUrl} target="_blank" rel="noreferrer" className="text-link">{right.canonicalName} source</a></div></section>
    {!preview && <><CommunityVote comparison={comparisonSlug} products={[{slug:left.slug,shortName:left.canonicalName},{slug:right.slug,shortName:right.canonicalName}]} useCaseKey={preset} attributeOptions={smartphoneFields.filter((f)=>f.direction && a[f.key]!==undefined && b[f.key]!==undefined).map((f)=>({key:f.key,label:f.label}))} /><div className="grid gap-5 md:grid-cols-2"><RetailerOffers productName={left.canonicalName} offers={offers.left} comparisonSlug={comparisonSlug}/><RetailerOffers productName={right.canonicalName} offers={offers.right} comparisonSlug={comparisonSlug}/></div></>}
  </div>;
}
