import Link from "next/link";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/site-header";
import { buyingGuides,isGuideCategory } from "@/lib/buying-guides";
import { DecisionPageEvent } from "@/components/decision-page-event";
type Props={params:Promise<{category:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {category}=await params;if(!isGuideCategory(category))return{title:"Guide not found",robots:{index:false}};const guide=buyingGuides[category];return{title:guide.title,description:guide.intro,alternates:{canonical:`https://bettrthan.com/guides/${category}`}};}
export default async function Guide({params}:Props){const {category}=await params;if(!isGuideCategory(category))notFound();const guide=buyingGuides[category];return <main><SiteHeader/><DecisionPageEvent event="guide_viewed" category={category}/><article className="mx-auto max-w-3xl px-5 py-10"><Link href="/guides" className="text-link">All buying guides</Link><p className="section-kicker mt-8">Bettr Than buying guide</p><h1 className="mt-3 text-3xl font-black sm:text-4xl">{guide.title}</h1><p className="mt-5 text-lg leading-8 text-slate-300">{guide.intro}</p><p className="mt-4 text-sm text-slate-400">Editorial guidance · Updated September 16, 2026 · Not a hands-on review</p>{guide.sections.map(([title,body])=><section key={title} className="mt-8"><h2 className="text-xl font-bold">{title}</h2><p className="mt-3 leading-7 text-slate-300">{body}</p></section>)}<section className="mt-10 rounded-3xl border border-cyan-300/20 p-6"><h2 className="text-xl font-bold">Put your priorities to work</h2><div className="mt-4 flex flex-wrap gap-5"><Link href={`/find?category=${category}&preset=${guide.preset}`} className="primary-action">Find my match</Link><Link href={`/category/${category}`} className="text-link">Browse products and comparisons</Link></div><p className="mt-4 text-sm text-slate-400">Product pages include manufacturer sources and checked dates. Inspect those sources for the exact configuration, measurement conditions, and current availability.</p></section><p className="mt-7 text-sm text-slate-400">Some purchase links may earn a commission. <Link href="/how-we-earn" className="text-link">How we earn</Link></p></article></main>;}
