export const buyingGuides = {
  headphones: { title:"How to choose headphones for your day", intro:"Start with where you listen and what interrupts you. A long feature list matters less than the trade-offs you will notice every day.", preset:"travel", sections:[
    ["Choose your listening situation","For commuting, compare noise cancellation, portability, and battery life with ANC enabled. For office use, look at multipoint and wired connections. A feature being present does not establish how well it works."],
    ["Compare battery claims on the same basis","Maximum battery life and battery life with ANC are different measurements. Use the ANC-on row when that is how you plan to listen, and check the manufacturer’s conditions."],
    ["Leave room for comfort","Weight is a useful fact, but it cannot tell you about clamping pressure, ear-pad fit, or long-session comfort. Check a retailer’s return policy before committing to a fit you have not tried."],
    ["Make a deliberate trade-off","Choose two candidates, try Travel, Office, and Value, and inspect which facts move the scores. USB-C charging alone does not establish USB audio support; use the explicit audio specification."] ] },
  smartphones: { title:"How to compare phones without chasing bigger numbers",intro:"Choose your operating system and spending limit first. Then compare the exact storage and regional configuration you would actually buy.",preset:"value",sections:[
    ["Set your non-negotiables","Use the finder to choose iOS or Android, a reference-price budget, and wireless charging if you need it. Confirm compatibility with your carrier and accessories on the manufacturer’s page."],
    ["Match the configuration","A launch price can refer to the lowest storage tier. Compare the price and capacity of the same configuration, then check the final retailer offer for condition and region."],
    ["Know what the numbers cannot tell you","Camera resolution alone does not measure photo quality. Battery capacity alone does not establish endurance, and a chipset name is not a performance test. Our phone scores deliberately avoid treating these as quality ratings."],
    ["Read the reason behind the winner","Balanced, Portability, and Value favor different priorities. A lower-weight phone may suit you better even when another model leads the balanced score. Inspect the source links before deciding."] ] },
  "portable-speakers": {title:"How to choose a portable speaker",intro:"The right speaker for a desk may be the wrong one for a bag. Decide how often you will carry it and where it will get wet before comparing features.",preset:"travel",sections:[
    ["Decide what portable means to you","Compare actual weight and the advertised battery figure. Manufacturer battery tests can use different volume and feature settings; the source conditions matter."],
    ["Separate water protection from other features","An ingress-protection rating and the ability to float are different facts. Use the explicit float filter if that is essential, and read the manufacturer’s usage limits."],
    ["Check connection requirements","USB audio, broadcast pairing, and charging another device are separate features. Do not assume a charging port supports an audio input."],
    ["Treat sound as a separate decision","The score summarizes published hardware. It does not measure tuning, loudness, distortion, or how the speaker sounds in your room. Use listening evidence alongside the specification comparison."]]},
  "vr-headsets": {title:"Choose a VR headset around the system you will use",intro:"Start with standalone or computer-connected use. Headsets can have impressive display specifications while requiring very different hardware and software setups.",preset:"standalone",sections:[
    ["Choose the platform before the score","If you need a headset that works without a PC, make standalone operation a must-have. Check the current manufacturer requirements for the applications you want to run."],
    ["Read resolution in context","Pixels per eye, refresh rate, and stated field of view describe different aspects of a display. They do not independently establish lens clarity or perceived image quality."],
    ["Account for the whole setup","Confirm what is included and whether controllers, a compatible computer, or other accessories are required. A headset reference price is not automatically the total setup cost."],
    ["Use an applicable preset","Standalone scoring needs two standalone headsets with battery evidence. PC & simulation weights display and tracking facts differently. An unavailable score is a data or applicability limit, not a product failure."]]},
  wearables: {title:"Choose a wearable that fits your phone and routine",intro:"A watch, ring, and fitness tracker solve different problems. Begin with compatibility and the way you want to wear the device, then compare features.",preset:"balanced",sections:[
    ["Check compatibility first","Use the iPhone or Android filter and verify the exact phone requirements with the manufacturer. Regional feature availability can differ from general device compatibility."],
    ["Choose the form factor","A smart ring prioritizes a different interaction style from a device with a display. Decide whether you need on-device information, built-in GPS, or a particular wearing style."],
    ["Include ongoing costs","Look for subscription costs and what functionality they unlock. Compare that ongoing commitment alongside the device’s reference price rather than treating the purchase as the whole cost."],
    ["Keep health claims in perspective","The presence of a sensor is not evidence of its accuracy or suitability for a medical purpose. Our comparison records features; it does not validate diagnostic performance. Check the manufacturer’s supported uses and regional restrictions."]]},
  "game-consoles": {title:"Choose a gaming system for where and what you play",intro:"A living-room console, hybrid system, and handheld PC are not interchangeable. Start with your games and preferred place to play.",preset:"balanced",sections:[
    ["Check the games and platform","Confirm that the specific games, subscriptions, and accessories you want work on the platform. A hardware score cannot settle a software-library preference."],
    ["Separate TV output from the built-in screen","Maximum output resolution and refresh rate are different from a handheld display’s specifications. Neither guarantees a particular game will run at that resolution or frame rate."],
    ["Plan storage and physical games","Check included storage, expansion options, and whether a disc drive is included. The exact product configuration matters when comparing prices."],
    ["Compare portable systems fairly","The Portable preset requires sourced display and battery information for both systems. Advertised battery ranges depend on workload; they are not a promise of identical endurance across games."]]},
} as const;
export type GuideCategory=keyof typeof buyingGuides;
export const isGuideCategory=(key:string):key is GuideCategory=>Object.hasOwn(buyingGuides,key);
